# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('dir', models.CharField(max_length=100)),
                ('generate_time', models.DateTimeField()),
                ('case_num', models.SmallIntegerField()),
                ('data', models.BinaryField()),
                ('name', models.CharField(max_length=100)),
                ('download_times', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('config', models.TextField()),
                ('user', models.CharField(max_length=50)),
                ('navi_version_id', models.IntegerField()),
                ('upload_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('state', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NaviVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.IntegerField()),
                ('version_name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField()),
            ],
        ),
    ]
