# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemaker', '0002_auto_20170617_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config',
            field=models.TextField(),
        ),
    ]
