# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemaker', '0003_auto_20170617_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='naviversion',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='add_time',
        ),
        migrations.AddField(
            model_name='case',
            name='config_id',
            field=models.IntegerField(default=1),
        ),
    ]
